name: sofvo
description: "ソフトバレーボール マッチングアプリ"
publish_to: 'none'
version: 1.0.50+67

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_database: ^12.1.3
  firebase_storage: ^13.0.6
  firebase_messaging: ^16.1.1
  google_fonts: ^8.0.1
  image_picker: ^1.2.1
  image_cropper: ^8.0.0
  file_picker: ^10.3.10
  url_launcher: ^6.3.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.9.0
  http: ^1.2.1
  csv: ^6.0.0
  share_plus: ^10.0.0
  gal: ^2.3.1
  path_provider: ^2.1.0
  sign_in_with_apple: ^6.1.4
  crypto: ^3.0.6
  cloud_functions: ^6.0.6
  package_info_plus: ^8.3.0
  app_links: ^6.4.0
  video_player: ^2.9.2
  chewie: ^1.8.5
  liquid_glass_widgets: ^1.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
